# Top menu for Carpentries & Lesson Programs
top:
  - name: The Carpentries
    url: https://carpentries.org
    weight: 10
  - name: Data Carpentry
    url: /
    weight: 20
    params:
      active: true
  - name: Library Carpentry
    url: https://librarycarpentry.org
    weight: 30
  - name: Software Carpentry
    url: https://software-carpentry.org
    weight: 40

# Main menu
main:
# Main menu: About
- identifier: about-us
  name: About us
  url: "/"
  parent: null
  weight: 10
- identifier: data-carpentry
  name: Data Carpentry
  url: "/about-us"
  parent: about-us
  weight: 10
- identifier: governance
  name: Governance
  pageRef: "/about-us/governance/"
  parent: about-us
  weight: 20
- identifier: curriculum-advisors
  name:  Curriculum Advisors
  url: "/about-us/curriculum-advisors/"
  parent: about-us
  weight: 30
# Learn Menu
- identifier: workshops
  name: Workshops
  url: "#"
  parent: null
  weight: 20
- identifier: workshops-upcoming
  name: Upcoming Workshops
  pageRef: "/workshops/workshops-upcoming/"
  parent: workshops
  weight: 10
- identifier: workshops-past
  name: Past Workshops
  pageRef: "/workshops/workshops-past/"
  parent: workshops
  weight: 20
# Lessons menu
- identifier: lessons
  name: Lessons
  url: "/lessons/"
  parent: null
  weight: 30
- identifier: astronomy
  name: Astronomy
  url: "/lessons/#astronomy"
  parent: lessons
- identifier: ecology
  name: Ecology
  url: "/lessons/#ecology"
  parent: lessons
- identifier: geospatial
  name: Geospatial
  url: "/lessons/#geospatial"
  parent: lessons
- identifier: genomics
  name: Genomics
  url: "/lessons/#genomics"
  parent: lessons
- identifier: image-processing
  name: Image processing
  url: "/lessons/#image-processing"
  parent: lessons
- identifier: social-science
  name: Social science
  url: "/lessons/#social-science"
  parent: lessons


footer:
# Footer menu: Menu 1 (About us)
- identifier: about-us-footer
  name: About The Carpentries
  url: "https://carpentries.orgabout-us/"
  parent: null
  weight: 10
- identifier: mission
  name: Our mission
  url: "https://carpentries.orgabout-us/#our-mission"
  parent: about-us-footer
  weight: 20
- identifier: history
  name: Our history
  url: "https://carpentries.orgabout-us/#our-history"
  parent: about-us-footer
  weight: 30
- identifier: values
  name: Our values
  url: "https://carpentries.orgabout-us/#our-values"
  parent: about-us-footer
  weight: 40
# Footer menu: Menu 2 (Our Community)
- identifier: community-footer
  name: Our community
  url: "#"
  parent: null
  weight: 20
- identifier: volunteers
  name: Our volunteers
  url: https://carpentries.orgcommunity/
  parent: community-footer
  weight: 20
- identifier: governance
  name: Our governance
  url: "https://carpentries.orgabout-us/governance/"
  parent: community-footer
  weight: 30
- identifier: get-involved
  name: Get involved
  url: "https://carpentries.orgcommunity/get-connected/"
  parent: community-footer
  weight: 40
# Footer menu: Menu 3 (Membership)
- identifier: membership-footer
  name: Membership
  url: "#"
  parent: null
  weight: 30
- identifier: membership-faq
  name: Membership FAQ
  url: "https://carpentries.orgsupport/membership/membership-faq/"
  parent: membership-footer
  weight: 20
- identifier: current-members
  name: Current members
  url: "https://carpentries.orgsupport/membership/member-list/"
  parent: membership-footer
  weight: 30
- identifier: become-member
  name: Become a member
  url: "https://carpentries.orgsupport/membership/"
  parent: membership-footer
  weight: 40
# Footer menu: Menu 4 (Workshops)
- identifier: workshops-footer
  name: Workshops
  url: "#"
  parent: null
  weight: 40
- identifier: workshops-faq
  name: Workshops FAQ
  url: "https://carpentries.orgworkshops/workshops-faq/"
  parent: workshops-footer
  weight: 10 
- identifier: workshops-upcoming
  name: Upcoming workshops
  url: "https://carpentries.orgworkshops/upcoming-workshops/"
  parent: workshops-footer
  weight: 20
- identifier: workshops-request
  name: Request a workshop
  url: "https://carpentries.orgworkshops/host-workshop/"
  parent: workshops-footer
  weight: 30
# Footer menu 5 (Lessons)
- identifier: lessons-footer
  name: Lessons
  url: "#"
  parent: null
  weight: 50
- identifier: lessons-search
  name: Search lessons
  url: "https://carpentries.orglessons/"
  parent: lessons-footer
  weight: 10
- identifier: lessons-instructor-training
  name: Instructor Training
  url: "https://carpentries.orginstructor-training/"
  parent: lessons-footer
  weight: 20
- identifier: lessons-trainer-training
  name: Instructor Trainer Training
  url: "https://carpentries.orgtrainer-training/"
  parent: lessons-footer
  weight: 30
# Footer menu 6 (Lesson Development)
- identifier: lesson-development-footer
  name: Lesson Development
  url: "#"
  parent: null
  weight: 60
- identifier: cldt-footer
  name: Collaborative Lesson Development Training
  url: "https://carpentries.orglesson-development/"
  parent: lesson-development-footer
  weight: 10
- indentifier: incubator-footer
  name: Carpentries Incubator
  url: "https://carpentries-incubator.org/"
  parent: lesson-development-footer
  weight: 20
- identifier: lab-footer
  name: Carpentries Lab
  url: "https://carpentries-lab.org/"
  parent: lesson-development-footer
  weight: 30
socials:
- name: Mastodon
  url: "https://hachyderm.io/@thecarpentries"
  params:
    img: "/mastodon-logo.svg"
  weight: 10
- name: LinkedIn
  url: "https://www.linkedin.com/company/the-carpentries/"
  params:
    img: "/linkedin-logo.svg"
  weight: 20
- name: Slack
  url: "https://swc-slack-invite.herokuapp.com/"
  params:
    img: "/slack-logo.svg"
  weight: 30
- name: Github
  url: "https://github.com/carpentries"
  params:
    img: "/github-logo.svg"
  weight: 40
- name: Zenodo
  url: "https://zenodo.org/communities/carpentries/records"
  params:
    img: "/zenodo-logo.svg"
  weight: 50
- name: Youtube
  url: "https://www.youtube.com/thecarpentries"
  params:
    img: "/youtube-logo.svg"
  weight: 60

