logo: dc_logo.png
logoAlt: Data Carpentry
logoFooter: dc_logo.png
logoFooterAlt: Data Carpentry

footer_overview_text: Data Carpentry is a lesson program of The Carpentries. 

git_repo: https://github.com/datacarpentry/new-website

carpentries_workshops_page: https://carpentries.orgworkshops/
carpentries_website: https://carpentries.org
carpentries_handbook: https://docs.carpentries.org 