logo: dc_logo.png
logoAlt: Data Carpentry
logoFooter: dc_logo.png
logoFooterAlt: Data Carpentry

footer_overview_text: Data Carpentry is a lesson program of The Carpentries. 

git_repo: https://github.com/datacarpentry/new-website

carpentries_workshops_page: https://carp-new-website.netlify.app/workshops/
carpentries_website: https://carp-new-website.netlify.app/
carpentries_handbook: https://docs.carpentries.org 